export enum RealtimeConnectionState {
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  RECONNECTING = 'RECONNECTING',
  DEGRADED = 'DEGRADED',
  OFFLINE = 'OFFLINE'
}

